DROP DATABASE if exists TRIPPLANNER_USERS;
CREATE DATABASE TRIPPLANNER_USERS;
USE  TRIPPLANNER_USERS;
 
-- CREATE USERS TABLE  
CREATE TABLE USERS( 
USER_ID INT AUTO_INCREMENT,
USER_NAME VARCHAR(20) NOT NULL,
EMAIL_ID VARCHAR(30) NOT NULL UNIQUE,
PASSWORD VARCHAR(70) NOT NULL,
REFRESH_TOKEN VARCHAR(70) NOT NULL,
constraint WL_USERS_Pk primary key ( USER_ID )
);

commit;